feat: Item sort dropdown
erpnext/hub pull request #56
Opened 2019-12-04 14:08 UTC by Mangesh-Khairnar

add sorting logic for the drop down feature

2019-12-24 10:43 UTC, netchampfaris requested changes

2019-12-24 10:43 UTC, netchampfaris commented on hub/hub/api.py
> +def get_items(keyword='', hub_seller=None, company=None, filters={}, order_by=None, limit=None, based_on=None, sort_order='desc'):
rename `based_on` to `sort_field`

2019-12-26 10:08 UTC, Mangesh-Khairnar commented on hub/hub/api.py
> +def get_items(keyword='', hub_seller=None, company=None, filters={}, order_by=None, limit=None, based_on=None, sort_order='desc'):
added changes

2019-12-27 09:15 UTC, netchampfaris approved these changes

2019-12-27 09:16 UTC, merged